### PR TITLE
PoloniexTradingAPIClient: Fix temporary object error.

### PR DESCRIPTION
**Pull request by Barrett17**
Just a little fix to an error that came out in Eclipse.

### CODE REVIEW

**Comment by TheCookieLab** [comment]
Thanks for the pull request. This library is Java 8 based. From your pull request it looks like you are getting an error on the ArrayList diamond notation is that correct? You can "resolve" this error by setting your Java JDK to 8.

**Comment by Barrett17** [comment]
Yes, the error is due to the diamond notation, I'm running openjdk 8 though

**Comment by Barrett17** [comment]
Thanks for applying the pr :)

The API looks like well done, that's why I chosen it, I've started to look into poloniex just a few days ago so I might be wrong, but I think there's some room for improvements in the library :

What about adding a complete list of currency pairs? Even if they will change from time to time it might make the API usage easier, especially when showing the data in a GUI.

I'm also working on a observer class which will retrieve data about the price and transactions in a backend thread, ideally it should work in a temporized way. Is there some design reason for not supplying something like that in the library itself? I'm thinking about an event-based layer.

**Comment by TheCookieLab** [comment]
I typically implement features in an MVP-first, iterative approach. 

As for an event subscriber, Poloniex has a websocket API as well. I have that in a separate library, which is not yet on Github.

**Comment by Barrett17** [comment]
Yes, with some hindsight it's probably not a good idea to hardcode currency pairs.

Why not integrate this feature in the library? I'd be interested eventually to submit a pull request.

**Pull request merged**
